name: temp
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - annotated-types=0.7.0
  - anyio=4.11.0
  - bzip2=1.0.8
  - ca-certificates=2025.10.5
  - certifi=2025.10.5
  - colorama=0.4.6
  - distro=1.9.0
  - exceptiongroup=1.3.0
  - h11=0.16.0
  - h2=4.3.0
  - hpack=4.1.0
  - httpcore=1.0.9
  - httpx=0.28.1
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.11
  - jiter=0.12.0
  - ld_impl_linux-64=2.44
  - libexpat=2.7.1
  - libffi=3.5.2
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - liblzma=5.8.1
  - libnsl=2.0.1
  - libsqlite=3.51.0
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libuuid=2.41.2
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - ncurses=6.5
  - openai=2.7.2
  - openssl=3.6.0
  - pydantic=2.12.4
  - pydantic-core=2.41.5
  - python=3.10.19
  - python_abi=3.10
  - readline=8.2
  - sniffio=1.3.1
  - tk=8.6.13
  - tqdm=4.67.1
  - typing-extensions=4.15.0
  - typing-inspection=0.4.2
  - typing_extensions=4.15.0
  - wheel=0.45.1
  - zstd=1.5.7
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - annotated-doc==0.0.4
      - anthropic==0.71.0
      - apache-tvm-ffi==0.1.2
      - astor==0.8.1
      - async-timeout==5.0.1
      - attrs==25.4.0
      - blake3==1.0.8
      - blobfile==3.1.0
      - cachetools==6.2.2
      - cbor2==5.7.1
      - charset-normalizer==3.4.4
      - click==8.3.1
      - cloudpickle==3.1.2
      - compressed-tensors==0.12.2
      - cuda-bindings==13.0.3
      - cuda-pathfinder==1.3.2
      - cuda-python==13.0.3
      - cupy-cuda12x==13.6.0
      - depyf==0.20.0
      - dill==0.4.0
      - diskcache==5.6.3
      - dnspython==2.8.0
      - docstring-parser==0.17.0
      - einops==0.8.1
      - email-validator==2.3.0
      - fastapi==0.121.3
      - fastapi-cli==0.0.16
      - fastapi-cloud-cli==0.4.0
      - fastar==0.6.0
      - fastrlock==0.8.3
      - filelock==3.20.0
      - fire==0.7.1
      - flashinfer-python==0.5.2
      - frozenlist==1.8.0
      - fsspec==2025.10.0
      - gguf==0.17.1
      - google-ai-generativelanguage==0.6.15
      - google-api-core==2.28.1
      - google-api-python-client==2.187.0
      - google-auth==2.43.0
      - google-auth-httplib2==0.2.1
      - google-genai==1.51.0
      - google-generativeai==0.8.5
      - googleapis-common-protos==1.72.0
      - grpcio==1.76.0
      - grpcio-status==1.71.2
      - hf-xet==1.2.0
      - httplib2==0.31.0
      - httptools==0.7.1
      - huggingface-hub==0.36.0
      - inquirerpy==0.3.4
      - interegular==0.3.3
      - jinja2==3.1.6
      - jmespath==1.0.1
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - lark==1.2.2
      - llguidance==1.3.0
      - llvmlite==0.44.0
      - lm-format-enforcer==0.11.3
      - loguru==0.7.3
      - lxml==6.0.2
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - mdurl==0.1.2
      - mistral-common==1.8.5
      - model-hosting-container-standards==0.1.9
      - mpmath==1.3.0
      - msgpack==1.1.2
      - msgspec==0.19.0
      - multidict==6.7.0
      - networkx==3.4.2
      - ninja==1.13.0
      - numba==0.61.2
      - numpy==2.2.6
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cudnn-frontend==1.16.0
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-cutlass-dsl==4.2.1
      - nvidia-ml-py==13.580.82
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu12==12.8.90
      - openai-harmony==0.0.8
      - opencv-python-headless==4.12.0.88
      - outlines-core==0.2.11
      - packaging==25.0
      - pandas==2.3.3
      - partial-json-parser==0.2.1.1.post7
      - pfzy==0.3.4
      - pillow==12.0.0
      - pip==24.3.1
      - prometheus-client==0.23.1
      - prometheus-fastapi-instrumentator==7.1.0
      - prompt-toolkit==3.0.52
      - propcache==0.4.1
      - proto-plus==1.26.1
      - protobuf==5.29.5
      - psutil==7.1.3
      - py-cpuinfo==9.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pybase64==1.4.2
      - pycountry==24.6.1
      - pycryptodomex==3.23.0
      - pydantic-extra-types==2.10.6
      - pygments==2.19.2
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.2.1
      - python-json-logger==4.0.0
      - python-multipart==0.0.20
      - pytz==2025.2
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - ray==2.51.1
      - referencing==0.37.0
      - regex==2025.11.3
      - requests==2.32.5
      - rich==14.2.0
      - rich-toolkit==0.16.0
      - rignore==0.7.6
      - rpds-py==0.29.0
      - rsa==4.9.1
      - safetensors==0.7.0
      - scipy==1.15.3
      - sentencepiece==0.2.1
      - sentry-sdk==2.45.0
      - setproctitle==1.3.7
      - setuptools==80.9.0
      - shellingham==1.5.4
      - six==1.17.0
      - starlette==0.50.0
      - supervisor==4.3.0
      - sympy==1.14.0
      - tabulate==0.9.0
      - tenacity==9.1.2
      - termcolor==3.2.0
      - tiktoken==0.12.0
      - tokenizers==0.22.1
      - tomli==2.3.0
      - torch==2.9.0
      - torchaudio==2.9.0
      - torchvision==0.24.0
      - transformers==4.57.1
      - triton==3.5.0
      - typer==0.20.0
      - tzdata==2025.2
      - uritemplate==4.2.0
      - urllib3==2.5.0
      - uvicorn==0.38.0
      - uvloop==0.22.1
      - vllm==0.11.1
      - watchfiles==1.1.1
      - wcwidth==0.2.14
      - websockets==15.0.1
      - xformers==0.0.33.post1
      - xgrammar==0.1.25
      - yarl==1.22.0
prefix: /home/user/miniconda3/envs/temp
